server:
  port: 8888

spring:
  application:
    name: mango-config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/User/IdeaProjects/mango-app/mango-config-service/src/main/resources/config
