server:
  port: 1000
  error:
    include-binding-errors: always
    include-message: always

spring:
  cloud:
    gateway:
      routes:
        - id: mango-gateway-route
          uri: http://localhost:1000
          predicates:
            - Path=/

        - id: mango-main-route
          uri: http://localhost:1001
          predicates:
            - Path=/api/ping/**
          filters:
            - RewritePath=/api/(?<remaining>.*), /api/${remaining}
