server:
  port: 1000
  error:
    include-binding-errors: always
    include-message: always

jwt:
  secret: ${JWT_SECRET}

spring:
  cloud:
    gateway:
      routes:
        - id: mango-gateway-service
          uri: http://localhost:1000
          predicates:
              - Path=/api/v1/gateway/**

        - id: mango-profile-service
          uri: http://localhost:1001
          predicates:
            - Path=/api/v1/u/**

  sql:
    init:
      mode: always
      data-locations: classpath:user.sql