spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mango_app
    username: postgres
    password: g8292gwjo
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: false
      properties:
        hibernate:
          format_sql: true
