server:
  port: 1001
  error:
    include-binding-errors: always
    include-message: always

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
